const_MEDIA_DIR="/media"
const_USB_TARGET_MOUNT_POINT="/media/storage"
const_USB_SOURCE_MOUNT_POINT="/media/source"
const_CLOUD_MOUNT_POINT="/media/cloud"
const_IOS_MOUNT_POINT="/media/iOS"
const_INTERNAL_BACKUP_DIR="/media/internal"
const_WEB_ROOT_LBB="/var/www/little-backup-box"
const_LOGFILE="/var/www/little-backup-box/tmp/little-backup-box.log"
const_LOGFILE_SYNC="/var/www/little-backup-box/tmp/sync.log"
const_DISPLAY_LINES_LIMIT=10
const_DISPLAY_HOLD_SEC=2
const_DISPLAY_CONTENT_FOLDER="/var/www/little-backup-box/tmp/display-content"
const_DISPLAY_CONTENT_OLD_FILE="/var/www/little-backup-box/tmp/display-content-old.txt"
const_RCLONE_CONFIG_FILE="/media/rclone.conf"
const_STORAGE_DEV_MASK="sd"
const_CMD_RUNNER_LOCKFILE="/var/www/little-backup-box/cmd-runner.lock"
const_PROGRESS_DISPLAY_WAIT_SEC=3
const_IMAGE_DATABASE_FILENAME="images.db"
const_FILE_EXTENSIONS_LIST_JPG="jpg jpeg"
const_FILE_EXTENSIONS_LIST_HEIC="heic heif"
const_FILE_EXTENSIONS_LIST_RAW="3fr arw dcr dng cr2 cr3 crw fff gpr j6i k25 kc2 kdc mdc mrw nef nrw orf pef raw raf rw2 rwl sr2 srf srw x3f"
const_FILE_EXTENSIONS_LIST_VIDEO="avi lrv mp4"
const_FILE_EXTENSIONS_LIST_AUDIO="mp3 wav"
const_VIEW_GRID_COLUMNS=3
const_VIEW_MAGNIFYING_GLASS_ZOOM=10
const_VPN_DIR_OpenVPN='/etc/openvpn'
const_VPN_DIR_WireGuard='/etc/wireguard'
const_VPN_FILENAME_OpenVPN='openvpn.conf'
const_VPN_FILENAME_WireGuard='wg0.conf'
